spring:
  datasource:
    url: jdbc:sqlite:./ARMS.db
    driver-class-name: org.sqlite.JDBC
  main:
    web-application-type: none

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: entity